# Generated by Django 5.0.1 on 2024-01-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.TextField()),
                ('dateofexpense', models.DateField()),
                ('amount', models.IntegerField()),
                ('updatedat', models.TimeField()),
                ('createdby', models.CharField(max_length=200)),
            ],
        ),
    ]
